export {Loader} from './loader/index.tsx'
export {UserInfo} from './user-info/index'
export {CommentsList} from './comments-list/index'
export {PostDetails} from './post-details/index'
export {PostsList} from './posts-list/index'